
DROP DATABASE QUIZ; 
CREATE DATABASE QUIZ;

DROP TABLE TB_COMMENT;
DROP TABLE TB_BOARD;
DROP TABLE TB_MEMBER;
DROP TABLE TB_QUIZ;


SET foreign_key_checks = 0;
drop table TB_BOARD;
SET foreign_key_checks = 1;

