
DROP DATABASE QUIZ; 
CREATE DATABASE QUIZ;

DROP TABLE TB_BOARD;
DROP TABLE TB_COMMENT;
DROP TABLE TB_MEMBER;
DROP TABLE TB_QUIZ;


SELECT * FROM TB_BOARD;
SELECT * FROM TB_COMMENT;
SELECT * FROM TB_MEMBER;
SELECT * FROM TB_QUIZ;
