-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 21:18:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema QUIZ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QUIZ
-- -----------------------------------------------------
USE `quiz` ;

-- -----------------------------------------------------
-- Table `QUIZ`.`tb_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ`.`tb_member` (
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자 아이디\n',
  `USER_PW` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 비번\n',
  `USER_NM` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 이름',
  `USER_EMAIL` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 메일\n',
  `USER_PHONE` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 번호\n',
  `USER_HOBBY` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 취미\n',
  `USER_POINT` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 점수(랭킹)\n',
  PRIMARY KEY (`USER_ID`)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `QUIZ`.`tb_board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ`.`tb_board` (
  `BO_NUM`      INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판 번호\n',
  `BO_TIT`      VARCHAR(500) NOT NULL COMMENT '게시판 제목\n',
  `BO_CTNT`     VARCHAR(500) NULL DEFAULT NULL COMMENT '게시판 내용\n',
  `BO_HIT`      VARCHAR(20) NULL DEFAULT NULL COMMENT '게시판 조회수',
  `BO_REG_DATE` VARCHAR(20) NULL DEFAULT NULL COMMENT '게시판 등록일\n',
  `USER_ID`     VARCHAR(20) NOT NULL,
  PRIMARY KEY (`BO_NUM`),
  FOREIGN KEY (`USER_ID`) 
  REFERENCES `TB_MEMBER` (`USER_ID`)
) 
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `QUIZ`.`tb_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ`.`tb_comment` (
  `COM_NUM` INT(11) NOT NULL AUTO_INCREMENT COMMENT '댓글 번호\n',
  `COM_TIT` VARCHAR(500) NULL DEFAULT NULL COMMENT '댓글 제목\n',
  `COM_CTNT` VARCHAR(500) NULL DEFAULT NULL COMMENT '댓글 내용\n',
  `USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자 아이디\n',
  `BO_NUM` INT(11) NOT NULL,
  PRIMARY KEY (`COM_NUM`),
  FOREIGN KEY (`BO_NUM`)
  REFERENCES `TB_BOARD` (`BO_NUM`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `QUIZ`.`tb_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ`.`tb_quiz` (
  `QUIZ_LEVEL` INT(11) NOT NULL COMMENT '문제 레벨\n',
  `QUIZ_ID` INT(11) NOT NULL COMMENT '문제 고유값\n',
  `QUIZ_PORB` VARCHAR(500) NULL DEFAULT NULL COMMENT '문제\n',
  `QUIZ_DFTY` VARCHAR(20) NULL DEFAULT NULL COMMENT '난이도\n',
  `QUIZ_PRO_TYPE` VARCHAR(20) NULL DEFAULT NULL COMMENT '문제유형\n',
  `QUIZ_EX` VARCHAR(500) NULL DEFAULT NULL COMMENT '보기\n',
  `QUIZ_AW` VARCHAR(500) NULL DEFAULT NULL COMMENT '답\n',
  PRIMARY KEY (`QUIZ_LEVEL`, `QUIZ_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `quiz` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



